### ISSUE TITLE
HMR Error

### ISSUE THREAD

**Issue by goras** [RickWong/react-isomorphic-starterkit#96]
Hi! I am receiving the error below whenever I change the contents of /src/server.js. Updating other files seems to be working fine though. I just downloaded the latest version of the repo, 5.0.7, and ran "npm install" and "npm run watch".

```
[HMR] Cannot apply update.
[HMR] Error: Aborted because 3 is not accepted
      at hotApply (/Projects/react-isomorphic-starterkit/dist/server.js:318:31)
      at hotUpdateDownloaded (/Projects/react-isomorphic-starterkit/dist/server.js:231:13)
      at hotAddUpdateChunk (/Projects/react-isomorphic-starterkit/dist/server.js:211:13)
      at hotDownloadUpdateChunk (/Projects/react-isomorphic-starterkit/dist/server.js:4:12)
      at hotEnsureUpdateChunk (/Projects/react-isomorphic-starterkit/dist/server.js:221:13)
      at /Projects/react-isomorphic-starterkit/dist/server.js:193:14
      at hotDownloadManifest (/Projects/react-isomorphic-starterkit/dist/server.js:13:12)
      at Object.hotCheck [as check] (/Projects/react-isomorphic-starterkit/dist/server.js:172:12)
      at checkForUpdate [as _repeat] (/Projects/react-isomorphic-starterkit/dist/server.js:531:16)
      at wrapper [as _onTimeout] (timers.js:264:19)
[HMR] You need to restart the application!
```

**Comment by RickWong** [comment]
Thanks. I will add back `nodemon` to restart node again whenever this happens. Earlier I removed it in bdd8ddaf48d17d510fd721c9639203b59bc5f112 apparently it's necessary.

Instead of `node --harmony dist/server.js` we need to start with `nodemon ./dist/server.js -- --harmony`

**Comment by RickWong** [comment]
Fixed in 175302ac22159e69d661a4e566a289148dfb8b4b

**Comment by goras** [comment]
Just tried it out, it seems that I am still getting a HMR error when updating src/server.js.

```
[0][HMR] Cannot apply update.
[0][HMR] Error: Aborted because 3 is not accepted
[0]     at hotApply (/Users/projects/react-isomorphic-starterkit/dist/server.js:318:31)
[0]     at hotUpdateDownloaded (/Users/projects/react-isomorphic-starterkit/dist/server.js:231:13)
[0]     at hotAddUpdateChunk (/Users/projects/react-isomorphic-starterkit/dist/server.js:211:13)
[0]     at hotDownloadUpdateChunk (/Users/projects/react-isomorphic-starterkit/dist/server.js:4:12)
[0]     at hotEnsureUpdateChunk (/Users/projects/react-isomorphic-starterkit/dist/server.js:221:13)
[0]     at /Users/projects/react-isomorphic-starterkit/dist/server.js:193:14
[0]     at hotDownloadManifest (/Users/projects/react-isomorphic-starterkit/dist/server.js:13:12)
[0]     at Object.hotCheck [as check] (/Users/projects/react-isomorphic-starterkit/dist/server.js:172:12)
[0]     at checkForUpdate [as _repeat] (/Users/projects/react-isomorphic-starterkit/dist/server.js:531:16)
[0]     at wrapper [as _onTimeout] (timers.js:264:19)
[0] [HMR] You need to restart the application!
[0] error: Forever detected script exited with code: 0
[0] error: Script restart attempt #1
```

**Comment by RickWong** [comment]
@goras That error is normal. `src/server.js` is the entry point of the server so if it changes, then the server needs to be restarted. The restart should happen automatically though, since `forever` is used to restart the application once it exits.

Have you tried the latest release 5.1.3?

**Comment by edvardchen** [comment]
I still have the same issues when I  excuted  `npm run watch` on Windows 7 

`[HMR] Cannot apply update.
[HMR] Error: Aborted because 3 is not accepted
    at hotApply (d:\demos\react-isomorphic-starterkit\dist\server.js:342:31)
    at hotUpdateDownloaded (d:\demos\react-isomorphic-starterkit\dist\server.js:255:13)
    at hotAddUpdateChunk (d:\demos\react-isomorphic-starterkit\dist\server.js:235:13)
    at hotDownloadUpdateChunk (d:\demos\react-isomorphic-starterkit\dist\server.js:4:12)
    at hotEnsureUpdateChunk (d:\demos\react-isomorphic-starterkit\dist\server.js:245:13)
    at d:\demos\react-isomorphic-starterkit\dist\server.js:217:14
    at hotDownloadManifest (d:\demos\react-isomorphic-starterkit\dist\server.js:13:12)
    at Object.hotCheck [as check] (d:\demos\react-isomorphic-starterkit\dist\server.js:196:12)
    at checkForUpdate [as _repeat] (d:\demos\react-isomorphic-starterkit\dist\server.js:555:16)
    at wrapper [as _onTimeout] (timers.js:275:11)
[HMR] You need to restart the application!
error: Forever detected script exited with code: 0
error: Script restart attempt #3
[HMR] Waiting for server-side updates
==> ✅  Server is listening
==> �  Go to http://localhost:8000
[HMR] Cannot apply update.
[HMR] Error: Aborted because 3 is not accepted
    at hotApply (d:\demos\react-isomorphic-starterkit\dist\server.js:342:31)`
